[package]
name = "thread_playground"
version = "0.1.0"
authors = ["coatsd <daniel.e.coats@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
waitgroup = "0.1.2"
futures = "0.3.15"
